# Generated by Django 5.1 on 2024-08-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_boxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
