# Generated by Django 5.1 on 2024-08-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedProFileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/profile')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
