# Generated by Django 5.1 on 2024-08-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0006_uploadedprofileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedprofileimage',
            name='file',
            field=models.FileField(upload_to='uploads/profile/'),
        ),
    ]
